package router

import (
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5/pgxpool"
	_ "github.com/pavelc4/auriya-todolist-go/docs" // docs is generated by Swag CLI
	"github.com/pavelc4/auriya-todolist-go/internal/cache"
	"github.com/pavelc4/auriya-todolist-go/internal/http/handler"
	"github.com/pavelc4/auriya-todolist-go/internal/http/middleware"
	"github.com/pavelc4/auriya-todolist-go/internal/http/repository"
	"github.com/pavelc4/auriya-todolist-go/internal/http/service"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"golang.org/x/oauth2"
)

func New(db *pgxpool.Pool, googleConf, githubConf *oauth2.Config, userRepo *repository.UserRepository, jwtService *service.JWTService, cacheSvc *cache.Service) *gin.Engine {
	gin.SetMode(gin.ReleaseMode)
	r := gin.New()
	r.Use(gin.Logger(), gin.Recovery())
	r.Use(cors.Default())

	r.GET("/", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "Hello World",
			"status":  "OK",
		})
	})

	health := handler.NewHealthHandler(db)
	r.GET("/health", health.Health)

	// Swagger route
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	store := repository.NewStore(db)
	task := handler.NewTaskHandler(store, cacheSvc)
	auth := handler.NewAuthHandler(googleConf, githubConf, userRepo, jwtService)
	project := handler.NewProjectHandler(store)

	// auth routes
	// Google
	r.GET("/auth/google/login", auth.GoogleLogin)
	r.GET("/auth/google/callback", auth.GoogleCallback)
	// Github
	r.GET("/auth/github/login", auth.GitHubLogin)
	r.GET("/auth/github/callback", auth.GitHubCallback)

	api := r.Group("/api")
	api.Use(middleware.RateLimiter()) // Apply rate limiter middleware
	{
		api.POST("/register", auth.Register)
		api.POST("/login", auth.Login)

		protected := api.Group("/")
		protected.Use(middleware.AuthMiddleware(jwtService))
		{
			// Task routes
			protected.POST("/tasks", task.Create)
			protected.GET("/tasks/:id", task.Get)
			protected.GET("/tasks", task.List)
			protected.PATCH("/tasks/:id", task.Update)
			protected.DELETE("/tasks/:id", task.Delete)

			// Project routes
			protected.POST("/projects", project.Create)
			protected.GET("/projects", project.List)
			protected.GET("/projects/:id", project.Get)
			protected.PATCH("/projects/:id", project.Update)
			protected.DELETE("/projects/:id", project.Delete)
			protected.GET("/projects/:id/tasks", task.ListByProject) // New route
		}
	}

	r.NoRoute(func(c *gin.Context) {
		c.JSON(404, gin.H{
			"message": "Ngapain Bego",
			"error":   "Route not found",
		})
	})

	return r
}
