// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Status      string             `json:"status"`
	Priority    int32              `json:"priority"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ProjectID   pgtype.Int8        `json:"project_id"`
}

type User struct {
	ID             int64              `json:"id"`
	Email          string             `json:"email"`
	FullName       pgtype.Text        `json:"full_name"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	Password       *string            `json:"password"`
	Age            pgtype.Int4        `json:"age"`
	AvatarUrl      *string            `json:"avatar_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	LastLogin      pgtype.Timestamptz `json:"last_login"`
}
