basePath: /api
definitions:
  handler.CreateTaskRequest:
    properties:
      description:
        type: string
      due_date:
        description: RFC3339
        type: string
      priority:
        maximum: 5
        minimum: 1
        type: integer
      status:
        enum:
        - pending
        - in_progress
        - done
        type: string
      title:
        type: string
    required:
    - title
    type: object
  handler.ErrorResponse:
    properties:
      detail:
        type: string
      error:
        type: string
    type: object
  handler.TaskResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      due_date:
        type: string
      id:
        type: integer
      priority:
        type: integer
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for a todolist application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Auriya Todolist API
  version: "1.0"
paths:
  /tasks:
    post:
      consumes:
      - application/json
      description: Adds a new task to the user's todolist
      parameters:
      - description: Task to create
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/handler.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.TaskResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new task
      tags:
      - tasks
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
