name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go (latest stable)
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Build
      run: go build -ldflags="-s -w" -v -o auriya-todolist-go ./cmd/server

    - name: Compress binary
      run: tar -czvf auriya-todolist-go.tar.gz auriya-todolist-go

    - name: Test
      run: go test -v ./...

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: auriya-todolist-go
        path: ./auriya-todolist-go.tar.gz
